<style>
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        color: #003A65 !important;
    }

    li {
        display: list-item;
        list-style-position: inside;
    }
</style>
<section style="margin-top: 80px;" class="mb-5">
    <div class="container" style="width: 65%;">
        <h1 style="text-align: center;margin-bottom: 45px;"><strong>Syarat dan Ketentuan Umum</strong></h1>
        <p style="text-align: justify;">Selamat datang di RUMAHTINGGAL.id (PT Baracipta Esa Engineering) sebuah marketplace desain rumah untuk mewujudkan rumah idaman Anda dengan mudah, hemat dan tetap berkualitas. Saat Anda mengunjungi, mendaftar, berkomunikasi dan atau melakukan transaksi di rumahtinggal.id, maka anda mengikuti syarat dan ketentuan berikut.</p>
        <p style="text-align: justify;"><strong>Dengan menggunakan Layanan </strong><strong>RUMAHTINGGAL.id</strong><strong>, Anda setuju untuk mengikuti syarat dan ketentuan ini. Silahkan membaca syarat dan ketentuan ini secara seksama.</strong></p>
        <p style="text-align: justify;">Kami menawarkan Layanan Rumahtinggal.id secara luas dari pembelian desain rumah, jasa kustomisasi desain rumah sampai jasa pembangunan, syarat dan ketentuan tambahan dapat berlaku. Ketika Anda menggunakan rumahtinggal.id (sebagai contoh pembelian paket Lite, Full atau custom) Anda juga akan mengikuti pedoman, syarat dan ketentuan, serta persetujuan terkait dengan Layanan Rumahtinggal.id (&ldquo;<strong>Ketentuan Layanan</strong>&rdquo;).</p>
        <p style="text-align: justify;">Apabila Syarat dan Ketentuan umum ini tidak&nbsp;sesuai dengan Ketentuan Layanan, maka Ketentuan Layanan itulah yang berlaku.</p>
        <h2>Kebijakan Privasi</h2>
        <p>Mohon membaca Kebijakan Privasi (klik link ini) yang mengatur Anda di dalam menggunakan Layanan <strong>RUMAHTINGGAL.id</strong> ini</p>
        <p>&nbsp;</p>
        <h2>Komunikasi Elektronik</h2>
        <p style="text-align: justify;">Ketika Anda menggunakan apapun Layanan <strong>RUMAHTINGGAL.id</strong>, atau mengirimkan&nbsp;e-mail, pesan teks, dan komunikasi lainnya dari komputer atau perangkat mobile kepada kami, Anda telah berkomunikasi dengan kami secara elektronik. Anda setuju untuk menerima komunikasi dari kami secara elektronik. Kami berkomunikasi dengan variasi cara, seperti melalui&nbsp;e-mail, pesan teks, notifikasi dalam aplikasi, atau dengan mempublikasikan pemberitahuan dan pesan di dalam situs ini atau melalui Layanan <strong>RUMAHTINGGAL.id</strong> lainnya, seperti Message Center. Anda setuju dengan seluruh persetujuan, pemberitahuan, penjelasan, dan komunikasi lainnya yang kami sediakan kepada Anda secara elektronik telah memenuhi persyaratan hukum yang berhubungan dengan komunikasi tertulis.&nbsp;</p>
        <p style="text-align: justify;">&nbsp;</p>
        <h2>Hak Cipta/Copyright</h2>
        <p style="text-align: justify;">Seluruh konten termasuk di dalam atau yang dibuat tersedia melalui <strong>RUMAHTINGGAL.id</strong> apapun, termasuk namun tidak terbatas pada teks, grafik, logo, ikon, gambar, audioklip, unduhan digital, kompilasi data, dan software adalah milik dari <strong>RUMAHTINGGAL.id</strong> dan penyedia konten dan dilindungi oleh Hukum dan Undang-Undang Hak Cipta Indonesia dan/atau Internasional yang terkait. Kompilasi dari seluruh konten yang ada di dalam dan dibuat tersedia melalui <strong>RUMAHTINGGAL.id</strong> apapun adalah milik eksklusif <strong>RUMAHTINGGAL.id</strong> dan dilindungi oleh Hukum dan Undang-Undang Hak Cipta Indonesia dan/atau Internasional yang terkait.</p>
        <p>&nbsp;</p>
        <h2>Merek/Trademark</h2>
        <p style="text-align: justify;">Grafik, logo, judul halaman, ikon, skrip, dan nama layanan di dalam atau dibuat tersedia melalui <strong>RUMAHTINGGAL.id</strong> apapun adalah merek dagang atau&nbsp;trademark&nbsp;dari <strong>RUMAHTINGGAL.id</strong> di Indonesia dan negara lainnya. Hak dagang dan&nbsp;trade dress&nbsp;<strong>RUMAHTINGGAL.id</strong> tidak dapat digunakan berhubungan dengan layanan yang bukan merupakan milik <strong>RUMAHTINGGAL.id</strong>, dengan cara apapun yang mungkin menyebabkan kebingungan di antara pelanggan, atau dengan cara apapun yang meremehkan atau mendiskreditkan <strong>RUMAHTINGGAL.id</strong>. Hak dagang lainnya yang tidak dimiliki <strong>RUMAHTINGGAL.id</strong> yang muncul di dalam Layanan <strong>RUMAHTINGGAL.id</strong> adalah milik dari masing-masing pemiliknya, yang mungkin atau tidak berafiliasi dengan, berhubungan dengan, atau disponsori oleh <strong>RUMAHTINGGAL.id</strong>.</p>
        <p>&nbsp;</p>
        <h1><strong>Lisensi dan Akses</strong></h1>
        <p style="text-align: justify;">Dengan tunduk dan menjalankan syarat dan ketentuan ini dan pembayaran Anda atas biaya yang diwajibkan, <strong>RUMAHTINGGAL.id</strong> dan penyedia konten memberikan kepada Anda lisensi yang terbatas, non-eksklusif, tidak dapat dipindahtangankan, dan tidak dapat disublisensikan untuk mengakses dan menggunakan Produk <strong>RUMAHTINGGAL.id</strong> untuk keperluan yang bersifat pribadi dan non-komersial. Lisensi ini tidak termasuk penjualan kembali atau penggunaan komersial dari <strong>RUMAHTINGGAL.id</strong>, atau kontennya, bentuk pengumpulan apapun dan penggunaan dari daftar, deskripsi, atau harga dari produk, atau bentuk penggunaan turunan dari Layanan <strong>RUMAHTINGGAL.id</strong> atau kontennya, pengunduhan, penyalinan, atau penggunaan dari informasi akun untuk keuntungan dari pihak ketiga, penggunaan data mining, robot, dan pengumpulan data dan perangkat ekstraksi sejenis. Semua hak yang tidak diberikan kepada Anda dalam syarat dan ketentuan ini dicadangkan dan disimpan oleh <strong>RUMAHTINGGAL.id</strong> atau pemberi ijinnya, penyedia, penerbit, pemegang saham, atau penyedia konten lainnya. </p>
        <p style="text-align: justify;">Tidak ada Layanan <strong>RUMAHTINGGAL.id</strong> atau bagian apapun dari Layanan <strong>RUMAHTINGGAL.id</strong> yang diperbolehkan untuk direproduksi, diduplikasi, disalin, dijual, dijual kembali, dikunjungi, atau hal lainnya untuk dieksploitasi dengan tujuan komersial tanpa adanya persetujuan tertulis dari <strong>RUMAHTINGGAL.id</strong>. Anda tidak diperbolehkan untuk melakukan&nbsp;framing&nbsp;atau menggunakan teknik&nbsp;framing&nbsp;untuk menyamai trademark, logo, atau kepemilikan informasi lainnya (termasuk gambar, teks, tampilan halaman, atau bentuk) dari <strong>RUMAHTINGGAL.id</strong> tanpa adanya persetujuan tertulis. Anda tidak diperbolehkan untuk menggunakan&nbsp;meta tags&nbsp;atau &ldquo;hidden text&rdquo; untuk menggunakan nama <strong>RUMAHTINGGAL.id</strong> atau hak dagangnya tanpa adanya persetujuan tertulis dari <strong>RUMAHTINGGAL.id</strong>. Anda tidak diperbolehkan untuk menyalahgunakan Layanan <strong>RUMAHTINGGAL.id.</strong> Anda diperbolehkan menggunakan Layanan <strong>RUMAHTINGGAL.id</strong> sesuai dengan yang diizinkan oleh hukum. Lisensi yang diberikan oleh <strong>RUMAHTINGGAL.id</strong> dapat dihentikan apabila Anda gagal untuk tunduk dan menjalankan syarat dan ketentuan ini.</p>
        <p>&nbsp;</p>
        <h1><strong>Akun Anda</strong></h1>
        <p style="text-align: justify;">Apabila Anda menggunakan Layanan <strong>RUMAHTINGGAL.id</strong>, Anda bertanggung jawab di dalam menjaga kerahasiaan dari akun dan kata sandi Anda dan membatasi akses komputer Anda, dan Anda setuju untuk menerima seluruh tanggung jawab atas aktifitas di bawah akun atau kata sandi Anda. Apabila Anda berusia di bawah 18 tahun, Anda hanya diperbolehkan menggunakan Layanan <strong>RUMAHTINGGAL.id</strong> hanya dengan pengawasan dari orang tua atau wali.</p>
        <p>&nbsp;</p>
        <h1><strong>Ulasan, Komentar, Komunikasi, dan Konten Lainnya</strong></h1>
        <p style="text-align: justify;">Pengunjung diperbolehkan untuk mempublikasikan ulasan, komentar, foto, video, dan konten lainnya; mengirimkan&nbsp;e-cards&nbsp;dan komunikasi lainnya; dan memberikan sugesti, ide, komentar, pertanyaan, atau informasi lainnya, selama konten tidak illegal, pornografi, mengancam, fitnah, menyerang privasi, melanggar hak kekayaan intelektual (termasuk hak publikasi), atau hal lainnya yang merugikan dan memberatkan pihak ketiga, dan tidak mengandung&nbsp;software&nbsp;virus, kampanye politis, ajakan komersial, pesan berantai,&nbsp;mass mailing, atau bentuk spam lainnya atau bentuk pesan yang tidak diinginkan lainnya. Anda tidak diperbolehkan menggunakan alamat email palsu, mengaku sebagai orang atau entitas lain, atau menyesatkan terkait dengan informasi kartu atau konten lainnya. <strong>RUMAHTINGGAL.id</strong> memiliki hak namun tidak berkewajiban untuk menghapus atau mengedit konten tersebut, namun tidak melakukan ulasan atas konten yang dipublikasikan secara berkala.</p>
        <p style="text-align: justify;">Apabila Anda mempublikasikan konten atau mengirimkan materi, dan kecuali Anda menyatakan sebaliknya, Anda memberikan hak non-eksklusif, bebas royalti, berkelanjutan, tidak dapat dibatalkan, dan secara penuh kepada <strong>RUMAHTINGGAL.id</strong> untuk menggunakan, reproduksi, memodifikasi, mengadaptasi, mempublikasikan, mentranslasi, dan membuat pekerjaan turunan, mendistribusikan, dan memperlihatkan konten tersebut ke seluruh dunia dengan media apapun. Anda memberikan kepada <strong>RUMAHTINGGAL.id</strong> dan sublisensinya hak untuk menggunakan nama yang Anda gunakan dalam mengirimkan konten tersebut. &nbsp;Anda merepresentasikan dan menjamin bahwa Anda memiliki kontrol dan hak dari konten yang ada publikasikan; keakuratan dari konten; dan penggunaan konten yang Anda sediakan tidak melanggar kebijakan ini dan tidak akan merugikan orang atau entitas manapun; dan Anda akan menanggung kerugian atas klaim yang mungkin terjadi atas publikasi konten yang Anda sediakan. <strong>RUMAHTINGGAL.id</strong> berhak namun tidak berkewajiban untuk mengawasi dan mengedit atau menghapus aktifitas atau konten apapun. <strong>RUMAHTINGGAL.id</strong> tidak memiliki tanggung jawab dan mengasumsikan tidak memiliki kewajiban atas konten yang Anda atau pihak ketiga publikasikan.</p>
        <p>&nbsp;</p>
        <h1><strong>Hubungan Hukum</strong></h1>
        <p style="text-align: justify;">Ketika Anda menggunakan jasa profesional dalam <strong>RUMAHTINGGAL.id</strong>, maka Anda dan profesional akan terikat dalam suatu perjanjian di antaranya dan tidak dengan <strong>RUMAHTINGGAL.id</strong>. <strong>RUMAHTINGGAL.id</strong> adalah penyedia platform yang mempertemukan Anda dan profesional yang Anda butuhkan. Oleh karena itu, setiap tuntutan yang timbul sehubungan dengan pelaksanaan pekerjaan profesional merupakan tuntutan yang ditujukan kepada profesional serta bukan kepada <strong>RUMAHTINGGAL.id</strong>.</p>
        <p>&nbsp;</p>
        <h1><strong>Izin Aplikasi</strong></h1>
        <p style="text-align: justify;">Ketika Anda menggunakan aplikasi yang dibuat oleh <strong>RUMAHTINGGAL.id</strong>, Anda akan memberikan beberapa hak akses kepada kami pada perangkat Anda. Kebanyakan dari perangkat mobile menyediakan informasi terkait dengan hak akses ini.</p>
        <p>&nbsp;</p>
        <h1><strong>Syarat </strong><strong>aplikasi </strong><strong>RUMAHTINGGAL.id</strong></h1>
        <p style="text-align: justify;">Menambahkan Syarat dan Ketentuan umum ini, syarat aplikasi (klik link ini) dijalankan untuk aplikasi manapun (termasuk pembaruan dari aplikasi dan dokumentasi terkait) yang kami buat tersedia bagi Anda dari waktu ke waktu untuk kegunaan Anda terkait dengan <strong>RUMAHTINGGAL.id</strong></p>
        <p>&nbsp;</p>
        <h1><strong>Bisnis lainnya</strong></h1>
        <p style="text-align: justify;">Pihak lainnya selain <strong>RUMAHTINGGAL.id</strong> yang mengoperasikan toko desain, menyediakan jasa dan layanan atau menjual lini produk melalui Layanan <strong>RUMAHTINGGAL.id</strong>. Sebagai tambahan, kami menyediakan link ke situs-situs perusahaan afiliasi dan beberapa bisnis lainnya. Kami tidak bertanggung jawab dalam memeriksa atau mengevaluasi, dan kami tidak menjamin penawaran dari bisnis atau individu atau konten dari situs web tersebut. <strong>RUMAHTINGGAL.id</strong> tidak mengasumsikan pertanggung jawaban atau kewajiban atas tindakan, produk, dan konten dari semuanya itu dan pihak ketiga lainnya. Silahkan membaca syarat dan ketentuan mereka secara seksama.</p>
        <p>&nbsp;</p>
        <h1><strong>Penolakan Jaminan dan Pembatasan Tanggung Jawab</strong></h1>
        <p style="text-align: justify;">Layanan <strong>RUMAHTINGGAL.id</strong> dan seluruh informasi, konten, materi, produk (termasuk software) dan layanan lainnya yang termasuk di dalam atau dibuat tersedia melalui <strong>RUMAHTINGGAL.id</strong> disediakan oleh <strong>RUMAHTINGGAL.id</strong> dalam basis &ldquo;apa adanya&rdquo; dan &ldquo;sebagaimana tersedia&rdquo;, kecuali disebutkan lain secara tertulis. <strong>RUMAHTINGGAL.id</strong> tidak membuat pernyataan atau jaminan apapun, tersurat maupun tersirat, atas operasi dari Layanan <strong>RUMAHTINGGAL.id</strong>, atau informasi, konten, materi, produk (termasuk software) atau layanan lainnya termasuk di dalam atau dibuat tersedia melalui <strong>RUMAHTINGGAL.id</strong>, kecuali disebutkan lain secara tertulis. Anda dengan tegas setuju bahwa penggunaan layanan <strong>RUMAHTINGGAL.id</strong> merupakan risiko Anda.</p>
        <p style="text-align: justify;">Sejauh yang diizinkan oleh hukum yang berlaku, <strong>RUMAHTINGGAL.id</strong> menolak semua penjaminan baik tersurat maupun tersirat, termasuk namun tidak terbatas pada, jaminan tersirat penjualan dan kesesuaian untuk tujuan tertentu. <strong>RUMAHTINGGAL.id</strong> tidak menjamin bahwa Layanan <strong>RUMAHTINGGAL.id</strong>, informasi, konten, materi, produk (termasuk software) atau layanan lainnya termasuk dalam atau dibuat tersedia kepada Anda melalui layanan <strong>RUMAHTINGGAL.id</strong>, server <strong>RUMAHTINGGAL.id</strong> atau komunikasi elektronik yang dikirim dari <strong>RUMAHTINGGAL.id</strong> bebas dari virus atau komponen berbahaya lainnya. Kerusakan apapun yang timbul dari penggunaan Layanan <strong>RUMAHTINGGAL.id</strong>, atau dari informasi, konten, materi, produk (termasuk software) atau layanan lainnya yang termasuk di dalam atau dibuat tersedia kepada Anda melalui Layanan <strong>RUMAHTINGGAL.id</strong>, termasuk namun tidak terbatas pada kerugian langsung, tidak langsung, incidental, sebab-akibat, atau yang lainnya kecuali disebutkan lain secara tertulis adalah bukan merupakan tanggung jawab <strong>RUMAHTINGGAL.id</strong>.</p>
        <p style="text-align: justify;">Beberapa ketentuan hukum Indonesia tidak memperbolehkan pembatasan penjaminan tersirat atau pengecualian atau pembatasan dari beberapa kerugian. Apabila hukum ini berlaku untuk Anda, beberapa atau seluruh pelepasan tanggung jawab, pengecualian atau pembatasan mungkin tidakberlaku untuk Anda, dan Anda mungkin akan memiliki hak tambahan.</p>
        <p>&nbsp;</p>
        <h1><strong>Perselisihan</strong></h1>
        <p style="text-align: justify;">Perselisihan apapun atau klaim berkaitan dengan penggunaan Anda atas Layanan <strong>RUMAHTINGGAL.id</strong>, atau produk atau layanan yang dijual atau didistribusikan oleh <strong>RUMAHTINGGAL.id</strong> akan direferensikan dan diselesaikan oleh Pengadilan Negeri Sleman</p>
        <p>&nbsp;</p>
        <h1><strong>Hukum yang Berlaku</strong></h1>
        <p style="text-align: justify;">Dengan menggunakan Layanan ARSITAG apapun, Anda setuju bahwa Hukum Republik Indonesia akan mengatur syarat dan ketentuan ini dan perselisihan apapun yang mungkin muncul di antara Anda dengan <strong>RUMAHTINGGAL.id</strong>.</p>
        <p>&nbsp;</p>
        <h1><strong>Kebijakan, modifikasi, dan keterpisahan situs</strong></h1>
        <p style="text-align: justify;">Silahkan mengulas dan membaca kebijakan lainnya yang kami publikasikan di situs ini. Kebijakan ini akan mengatur bagaimana Anda menggunakan Layanan <strong>RUMAHTINGGAL.id</strong>. Kami berhak untuk membuat perubahan pada situs, kebijakan, syarat layanan, dan syarat dan ketentuan ini sewaktu-waktu. Jika suatu saat ada ketentuan pada Syarat &amp; Ketentuan ini yang menjadi tidak valid, hilang, atau atas alasan alasan apapun tidak dapat dijalankan, kondisi tersebut dianggap dipisahkan dan tidak akan mempengaruhi validitas dan keberlakukan dari kondisi yang ada.</p>
        <p>&nbsp;</p>
        <p>Alamat Kami</p>
        <p>PT Baracipta Esa Engineering</p>
        <p>Jl. Mijil No.mor 98, Karangjati, Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55284</p>
        <p>www.rumahtinggal.id</p>
        <p>&nbsp;</p>
    </div>
</section>